### ISSUE TITLE
Add Postgres Extension for Geolocation of Location table

### ISSUE THREAD

**Issue by yordis** [straw-hat-team/straw_hat_map#7]
- Elixir Package: https://github.com/bryanjos/geo 
- Elixir Package: https://github.com/bryanjos/geo_postgis
- Postgres Extension: http://postgis.net/

Preferiblemente que todo las respuestas sean GeoJSON: http://www.postgis.net/docs/ST_AsGeoJSON.html

**Comment by CamonZ** [comment]
@yordis what exactly is the end goal with the feature. Depending on what you want to store you need different types on your migrations for geodata.

Simple point-like geo features use the `st_point` type which I'm sure [geo_postgis]() has it defined. For more complex types you need to use either the generic `Geometry` type or specifically `Polygon` or `Multipolygon`.

Once you have the migration in place, you can store geodata from multiple input sources, for example you could use [`ST_GeomFromGeoJSON`](http://postgis.net/docs/ST_GeomFromGeoJSON.html) to import geojson data directly into the db, and output it directly as geojson with `ST_AsGeoJSON`

**Comment by yordis** [comment]
@CamonZ right now we need the `st_point` for the location that will represent the `lan,lon` of the it
